/* Body file for function vizkit3d_Robot
 * Generated by TASTE on 2021-06-09 11:02:39
 * Provided interfaces : updateJoints, updateRigidBodyState
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 1432 432 1783 647
 * Timers              : 
 */
#include "vizkit3d_robot_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned vizkit3d_robot_initialized = 0;
void init_vizkit3d_robot(void)
{
   if (!vizkit3d_robot_initialized) {
      vizkit3d_robot_initialized = 1;
      // Call user code startup function
      vizkit3d_robot_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function vizkit3d_Robot");
#endif
      vizkit3d_robot_initialized = 2;
   }
}
void vizkit3d_robot_updateJoints
      (const char *IN_joints, size_t IN_joints_len)

{

   static asn1SccBase_commands_Joints IN_JOINTS;
#ifdef __unix__
   asn1SccBase_commands_Joints_Initialize(&IN_JOINTS);
#endif
   if (0 != Decode_NATIVE_Base_commands_Joints (&IN_JOINTS, (void *)IN_joints, IN_joints_len)) {
      #ifdef __unix__
         puts("Error decoding Base-commands-Joints in function vizkit3d_Robot_updateJoints");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void vizkit3d_robot_PI_updateJoints
      (const asn1SccBase_commands_Joints *);




   // Call user code
   vizkit3d_robot_PI_updateJoints (&IN_JOINTS);

}
void vizkit3d_robot_updateRigidBodyState
      (const char *IN_rbs, size_t IN_rbs_len)

{

   static asn1SccBase_samples_RigidBodyState IN_RBS;
#ifdef __unix__
   asn1SccBase_samples_RigidBodyState_Initialize(&IN_RBS);
#endif
   if (0 != Decode_NATIVE_Base_samples_RigidBodyState (&IN_RBS, (void *)IN_rbs, IN_rbs_len)) {
      #ifdef __unix__
         puts("Error decoding Base-samples-RigidBodyState in function vizkit3d_Robot_updateRigidBodyState");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void vizkit3d_robot_PI_updateRigidBodyState
      (const asn1SccBase_samples_RigidBodyState *);




   // Call user code
   vizkit3d_robot_PI_updateRigidBodyState (&IN_RBS);

}

