/* Body file for function vizkit3d_Robot
 * Generated by TASTE on 2021-06-09 11:02:39
 * You can edit this file, it will not be overwritten
 * Provided interfaces : updateJoints, updateRigidBodyState
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 1432 432 1783 647
 * Timers              : 
 */
/* There are no required interfaces for this function... */

