/* ASN.1 System configuration file for function vizkit3d_Robot
 * Generated by TASTE on 2021-06-09 11:02:39
 */
#define __NEED_Base_commands_Joints_NATIVE
#define __NEED_Base_samples_RigidBodyState_NATIVE
