/* Body file for function vizkit3d_DepthMap
 * Generated by TASTE on 2021-06-09 12:03:09
 * Provided interfaces : updateDepthMap, updatePose
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 1003 394 1393 553
 * Timers              : 
 */
#include "vizkit3d_depthmap_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned vizkit3d_depthmap_initialized = 0;
void init_vizkit3d_depthmap(void)
{
   if (!vizkit3d_depthmap_initialized) {
      vizkit3d_depthmap_initialized = 1;
      // Call user code startup function
      vizkit3d_depthmap_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function vizkit3d_DepthMap");
#endif
      vizkit3d_depthmap_initialized = 2;
   }
}
void vizkit3d_depthmap_updateDepthMap
      (const char *IN_map, size_t IN_map_len)

{

   static asn1SccBase_samples_DepthMap IN_MAP;
#ifdef __unix__
   asn1SccBase_samples_DepthMap_Initialize(&IN_MAP);
#endif
   if (0 != Decode_NATIVE_Base_samples_DepthMap (&IN_MAP, (void *)IN_map, IN_map_len)) {
      #ifdef __unix__
         puts("Error decoding Base-samples-DepthMap in function vizkit3d_DepthMap_updateDepthMap");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void vizkit3d_depthmap_PI_updateDepthMap
      (const asn1SccBase_samples_DepthMap *);




   // Call user code
   vizkit3d_depthmap_PI_updateDepthMap (&IN_MAP);

}
void vizkit3d_depthmap_updatePose
      (const char *IN_pose, size_t IN_pose_len)

{

   static asn1SccBase_samples_RigidBodyState IN_POSE;
#ifdef __unix__
   asn1SccBase_samples_RigidBodyState_Initialize(&IN_POSE);
#endif
   if (0 != Decode_NATIVE_Base_samples_RigidBodyState (&IN_POSE, (void *)IN_pose, IN_pose_len)) {
      #ifdef __unix__
         puts("Error decoding Base-samples-RigidBodyState in function vizkit3d_DepthMap_updatePose");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void vizkit3d_depthmap_PI_updatePose
      (const asn1SccBase_samples_RigidBodyState *);




   // Call user code
   vizkit3d_depthmap_PI_updatePose (&IN_POSE);

}

