
/* Header file for function vizkit3d_SonarBeam in CPP language
 * Generated by TASTE on 2021-07-14 18:46:54
 * Context Parameters present : YES
 * Provided interfaces : updateOrientation, updateSonarBeam
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = enabled
  *  |_ Taste::coordinates = 1004 757 1394 911
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void vizkit3d_sonarbeam_startup(void);

/* Provided interfaces */
void vizkit3d_sonarbeam_PI_updateOrientation( const asn1SccBase_samples_RigidBodyState * );
void vizkit3d_sonarbeam_PI_updateSonarBeam( const asn1SccBase_samples_SonarBeam * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif

