
/* Header file for function vizkit3d_Pointcloud in CPP language
 * Generated by TASTE on 2021-07-14 18:46:54
 * Context Parameters present : YES
 * Provided interfaces : updatePointCloud
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = enabled
  *  |_ Taste::coordinates = 1001 212 1391 371
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void vizkit3d_pointcloud_startup(void);

/* Provided interfaces */
void vizkit3d_pointcloud_PI_updatePointCloud( const asn1SccBase_samples_Pointcloud * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif

