
/* Header file for function vizkit3d_BodyState in CPP language
 * Generated by TASTE on 2021-07-14 18:50:24
 * Context Parameters present : YES
 * Provided interfaces : updateBodyState
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = enabled
  *  |_ Taste::coordinates = 1440 567 1763 724
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void vizkit3d_bodystate_startup(void);

/* Provided interfaces */
void vizkit3d_bodystate_PI_updateBodyState( const asn1SccBase_samples_BodyState * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif

