#!/bin/bash -e

# This script will build your system
# DO NOT EDIT THIS FILE

# this file was genrated for backward compatibility (legacy)
# but it is deprecated in favour of the Makefile

# Generated by kazoo on 

CWD=$(pwd)

if [ -t 1 ] ; then
    COLORON="\e[1m\e[32m"
    COLOROFF="\e[0m"
else
    COLORON=""
    COLOROFF=""
fi

INFO="${COLORON}[INFO]${COLOROFF}"

make
