/* Body file for function vizkit3d_Pointcloud
 * Generated by TASTE on 2021-06-09 12:03:09
 * You can edit this file, it will not be overwritten
 * Provided interfaces : updatePointCloud
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 1001 212 1391 371
 * Timers              : 
 */
/* There are no required interfaces for this function... */

