/* Header file for function vizkit3d_Pointcloud in CPP language
 * Generated by TASTE on 2021-06-09 12:03:09
 * Context Parameters present : YES
 * Provided interfaces : updatePointCloud
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = enabled
  *  |_ Taste::coordinates = 1001 212 1391 371
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#ifdef __cplusplus
extern "C" {
#endif

#include "vizkit3d_pointcloud.h"

// Function initialization - calls user startup code of all dependent functions
void init_vizkit3d_pointcloud(void);


/* Provided interfaces */
void vizkit3d_pointcloud_updatePointCloud
      (const char *IN_cloud, size_t IN_cloud_len);


#ifdef __cplusplus
}
#endif

