/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Context-vizkit3d-robot.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccContext_vizkit3d_robot_Initialize(asn1SccContext_vizkit3d_robot* pVal)
{
    *pVal = (asn1SccContext_vizkit3d_robot) {
    .configfile = "",
    .id = " "
};
}
#endif

 
flag asn1SccContext_vizkit3d_robot_IsConstraintValid(const asn1SccContext_vizkit3d_robot* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccVizkit3D_FilePath_IsConstraintValid(pVal->configfile, pErrCode);
	if (ret) {
	    ret = asn1SccVizkit3D_PluginLabel_IsConstraintValid(pVal->id, pErrCode);
	
	}

	return ret;
}

const asn1SccContext_vizkit3d_robot vizkit3d_robot_ctxt = {
    .configfile = "config-robot.yml",
    .id = "Robot"
};
