/* Body file for function test_Robot
 * Generated by TASTE on 2021-06-09 11:02:39
 * Provided interfaces : trigger
 * Required interfaces : updateJoints, updateRigidBodyState
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 524 430 956 650
 * Timers              : 
 */
#include "test_robot_vm_if.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned test_robot_initialized = 0;
void init_test_robot(void)
{
   if (!test_robot_initialized) {
      test_robot_initialized = 1;
      // Call user code startup function
      test_robot_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function test_Robot");
#endif
      test_robot_initialized = 2;
   }
}
void test_robot_trigger()
{
   //  Directly call user code, no parameters to pass
   extern void test_robot_PI_trigger(void);
   test_robot_PI_trigger();
   // puts ("test_robot_trigger called");
}

