/* Body file for function vizkit3d_LaserScan
 * Generated by TASTE on 2021-06-09 12:03:09
 * Provided interfaces : updateLaserScan, updatePose
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 1006 574 1396 733
 * Timers              : 
 */
#include "vizkit3d_laserscan_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned vizkit3d_laserscan_initialized = 0;
void init_vizkit3d_laserscan(void)
{
   if (!vizkit3d_laserscan_initialized) {
      vizkit3d_laserscan_initialized = 1;
      // Call user code startup function
      vizkit3d_laserscan_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function vizkit3d_LaserScan");
#endif
      vizkit3d_laserscan_initialized = 2;
   }
}
void vizkit3d_laserscan_updateLaserScan
      (const char *IN_scan, size_t IN_scan_len)

{

   static asn1SccBase_samples_LaserScan IN_SCAN;
#ifdef __unix__
   asn1SccBase_samples_LaserScan_Initialize(&IN_SCAN);
#endif
   if (0 != Decode_NATIVE_Base_samples_LaserScan (&IN_SCAN, (void *)IN_scan, IN_scan_len)) {
      #ifdef __unix__
         puts("Error decoding Base-samples-LaserScan in function vizkit3d_LaserScan_updateLaserScan");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void vizkit3d_laserscan_PI_updateLaserScan
      (const asn1SccBase_samples_LaserScan *);




   // Call user code
   vizkit3d_laserscan_PI_updateLaserScan (&IN_SCAN);

}
void vizkit3d_laserscan_updatePose
      (const char *IN_pose, size_t IN_pose_len)

{

   static asn1SccBase_samples_RigidBodyState IN_POSE;
#ifdef __unix__
   asn1SccBase_samples_RigidBodyState_Initialize(&IN_POSE);
#endif
   if (0 != Decode_NATIVE_Base_samples_RigidBodyState (&IN_POSE, (void *)IN_pose, IN_pose_len)) {
      #ifdef __unix__
         puts("Error decoding Base-samples-RigidBodyState in function vizkit3d_LaserScan_updatePose");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void vizkit3d_laserscan_PI_updatePose
      (const asn1SccBase_samples_RigidBodyState *);




   // Call user code
   vizkit3d_laserscan_PI_updatePose (&IN_POSE);

}

