/* This file was generated automatically - DO NOT MODIFY IT ! */

/* Configuration file used by C_ASN1_Types.h */

#define __NEED_Base_samples_Pointcloud_NATIVE
#define __NEED_Base_samples_DepthMap_NATIVE
#define __NEED_Base_samples_RigidBodyState_NATIVE
#define __NEED_Base_samples_LaserScan_NATIVE
#define __NEED_Base_samples_RigidBodyState_NATIVE
#define __NEED_Base_samples_SonarBeam_NATIVE
#define __NEED_Base_samples_RigidBodyState_NATIVE
#define __NEED_Base_samples_Pointcloud_NATIVE
#define __NEED_Base_samples_DepthMap_NATIVE
#define __NEED_Base_samples_RigidBodyState_NATIVE
#define __NEED_Base_samples_LaserScan_NATIVE
#define __NEED_Base_samples_RigidBodyState_NATIVE
#define __NEED_Base_samples_SonarBeam_NATIVE
#define __NEED_Base_samples_RigidBodyState_NATIVE
