/* Body file for function test_Range
 * Generated by TASTE on 2021-06-09 12:03:09
 * You can edit this file, it will not be overwritten
 * Provided interfaces : trigger
 * Required interfaces : updateDepthMap, updateLaserScan, updateOrientation, updatePointCloud, updatePose_DM, updatePose_LS, updateSonarBeam
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 265 199 655 406
 * Timers              : 
 */
#include <stdlib.h>
#ifdef __unix__
   #include <stdio.h>
   #include "PrintTypesAsASN1.h"
   #include "timeInMS.h"
#endif
#include "C_ASN1_Types.h"
#include "dataview-uniq.h"

// reference to flag preventing calls to RIs during the startup transition
extern unsigned test_range_initialized;
// in case that happens, use system's abort function to crash the application
extern void abort (void);

void test_range_RI_updateDepthMap
      (const asn1SccBase_samples_DepthMap *IN_map)

{
   // Check that we are not in the startup transition
   if (2 != test_range_initialized) {
      #ifdef __unix__
         puts("A call to test_range_RI_updateDepthMap was made during system startup.");
         puts("This is not allowed because the system is not yet fully initialized. Please fix your code/models");
      #endif
      // crash the application
      abort();
   }

   #ifdef __unix__
      // Log MSC data on Linux when environment variable is set
      static int innerMsc = -1;
      if (-1 == innerMsc)
         innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
      if (1 == innerMsc) {
         long long msc_time = getTimeInMilliseconds();
         PrintASN1Base_samples_DepthMap ("INNERDATA: updatedepthmap::Base_samples_DepthMap::map", IN_map);
         puts(""); // add newline
         // Log message to vizkit3d_DepthMap (corresponding PI: updateDepthMap)
         printf ("INNER: test_range,vizkit3d_depthmap,updatedepthmap,%lld\n", msc_time);
         fflush(stdout);
      }
   #endif
   // Encode parameter map
   static asn1SccBase_samples_DepthMap IN_buf_map;
   int size_IN_buf_map =
      Encode_NATIVE_Base_samples_DepthMap
        ((void *)&IN_buf_map,
          sizeof(asn1SccBase_samples_DepthMap),
          (asn1SccBase_samples_DepthMap *)IN_map);
   if (-1 == size_IN_buf_map) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in test_range_RI_updateDepthMap, parameter map");
      #endif
        /* Crash the application due to message loss */
        abort();
   }


   // Call Middleware interface
   extern void vm_test_range_updatedepthmap
     (void *, size_t);

   vm_test_range_updatedepthmap
     ((void *)&IN_buf_map, (size_t)size_IN_buf_map);


}void test_range_RI_updateLaserScan
      (const asn1SccBase_samples_LaserScan *IN_scan)

{
   // Check that we are not in the startup transition
   if (2 != test_range_initialized) {
      #ifdef __unix__
         puts("A call to test_range_RI_updateLaserScan was made during system startup.");
         puts("This is not allowed because the system is not yet fully initialized. Please fix your code/models");
      #endif
      // crash the application
      abort();
   }

   #ifdef __unix__
      // Log MSC data on Linux when environment variable is set
      static int innerMsc = -1;
      if (-1 == innerMsc)
         innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
      if (1 == innerMsc) {
         long long msc_time = getTimeInMilliseconds();
         PrintASN1Base_samples_LaserScan ("INNERDATA: updatelaserscan::Base_samples_LaserScan::scan", IN_scan);
         puts(""); // add newline
         // Log message to vizkit3d_LaserScan (corresponding PI: updateLaserScan)
         printf ("INNER: test_range,vizkit3d_laserscan,updatelaserscan,%lld\n", msc_time);
         fflush(stdout);
      }
   #endif
   // Encode parameter scan
   static asn1SccBase_samples_LaserScan IN_buf_scan;
   int size_IN_buf_scan =
      Encode_NATIVE_Base_samples_LaserScan
        ((void *)&IN_buf_scan,
          sizeof(asn1SccBase_samples_LaserScan),
          (asn1SccBase_samples_LaserScan *)IN_scan);
   if (-1 == size_IN_buf_scan) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in test_range_RI_updateLaserScan, parameter scan");
      #endif
        /* Crash the application due to message loss */
        abort();
   }


   // Call Middleware interface
   extern void vm_test_range_updatelaserscan
     (void *, size_t);

   vm_test_range_updatelaserscan
     ((void *)&IN_buf_scan, (size_t)size_IN_buf_scan);


}void test_range_RI_updateOrientation
      (const asn1SccBase_samples_RigidBodyState *IN_rbs)

{
   // Check that we are not in the startup transition
   if (2 != test_range_initialized) {
      #ifdef __unix__
         puts("A call to test_range_RI_updateOrientation was made during system startup.");
         puts("This is not allowed because the system is not yet fully initialized. Please fix your code/models");
      #endif
      // crash the application
      abort();
   }

   #ifdef __unix__
      // Log MSC data on Linux when environment variable is set
      static int innerMsc = -1;
      if (-1 == innerMsc)
         innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
      if (1 == innerMsc) {
         long long msc_time = getTimeInMilliseconds();
         PrintASN1Base_samples_RigidBodyState ("INNERDATA: updateorientation::Base_samples_RigidBodyState::rbs", IN_rbs);
         puts(""); // add newline
         // Log message to vizkit3d_SonarBeam (corresponding PI: updateOrientation)
         printf ("INNER: test_range,vizkit3d_sonarbeam,updateorientation,%lld\n", msc_time);
         fflush(stdout);
      }
   #endif
   // Encode parameter rbs
   static asn1SccBase_samples_RigidBodyState IN_buf_rbs;
   int size_IN_buf_rbs =
      Encode_NATIVE_Base_samples_RigidBodyState
        ((void *)&IN_buf_rbs,
          sizeof(asn1SccBase_samples_RigidBodyState),
          (asn1SccBase_samples_RigidBodyState *)IN_rbs);
   if (-1 == size_IN_buf_rbs) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in test_range_RI_updateOrientation, parameter rbs");
      #endif
        /* Crash the application due to message loss */
        abort();
   }


   // Call Middleware interface
   extern void vm_test_range_updateorientation
     (void *, size_t);

   vm_test_range_updateorientation
     ((void *)&IN_buf_rbs, (size_t)size_IN_buf_rbs);


}void test_range_RI_updatePointCloud
      (const asn1SccBase_samples_Pointcloud *IN_cloud)

{
   // Check that we are not in the startup transition
   if (2 != test_range_initialized) {
      #ifdef __unix__
         puts("A call to test_range_RI_updatePointCloud was made during system startup.");
         puts("This is not allowed because the system is not yet fully initialized. Please fix your code/models");
      #endif
      // crash the application
      abort();
   }

   #ifdef __unix__
      // Log MSC data on Linux when environment variable is set
      static int innerMsc = -1;
      if (-1 == innerMsc)
         innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
      if (1 == innerMsc) {
         long long msc_time = getTimeInMilliseconds();
         PrintASN1Base_samples_Pointcloud ("INNERDATA: updatepointcloud::Base_samples_Pointcloud::cloud", IN_cloud);
         puts(""); // add newline
         // Log message to vizkit3d_Pointcloud (corresponding PI: updatePointCloud)
         printf ("INNER: test_range,vizkit3d_pointcloud,updatepointcloud,%lld\n", msc_time);
         fflush(stdout);
      }
   #endif
   // Encode parameter cloud
   static asn1SccBase_samples_Pointcloud IN_buf_cloud;
   int size_IN_buf_cloud =
      Encode_NATIVE_Base_samples_Pointcloud
        ((void *)&IN_buf_cloud,
          sizeof(asn1SccBase_samples_Pointcloud),
          (asn1SccBase_samples_Pointcloud *)IN_cloud);
   if (-1 == size_IN_buf_cloud) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in test_range_RI_updatePointCloud, parameter cloud");
      #endif
        /* Crash the application due to message loss */
        abort();
   }


   // Call Middleware interface
   extern void vm_test_range_updatepointcloud
     (void *, size_t);

   vm_test_range_updatepointcloud
     ((void *)&IN_buf_cloud, (size_t)size_IN_buf_cloud);


}void test_range_RI_updatePose_DM
      (const asn1SccBase_samples_RigidBodyState *IN_pose)

{
   // Check that we are not in the startup transition
   if (2 != test_range_initialized) {
      #ifdef __unix__
         puts("A call to test_range_RI_updatePose_DM was made during system startup.");
         puts("This is not allowed because the system is not yet fully initialized. Please fix your code/models");
      #endif
      // crash the application
      abort();
   }

   #ifdef __unix__
      // Log MSC data on Linux when environment variable is set
      static int innerMsc = -1;
      if (-1 == innerMsc)
         innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
      if (1 == innerMsc) {
         long long msc_time = getTimeInMilliseconds();
         PrintASN1Base_samples_RigidBodyState ("INNERDATA: updatepose_dm::Base_samples_RigidBodyState::pose", IN_pose);
         puts(""); // add newline
         // Log message to vizkit3d_DepthMap (corresponding PI: updatePose)
         printf ("INNER: test_range,vizkit3d_depthmap,updatepose_dm,%lld\n", msc_time);
         fflush(stdout);
      }
   #endif
   // Encode parameter pose
   static asn1SccBase_samples_RigidBodyState IN_buf_pose;
   int size_IN_buf_pose =
      Encode_NATIVE_Base_samples_RigidBodyState
        ((void *)&IN_buf_pose,
          sizeof(asn1SccBase_samples_RigidBodyState),
          (asn1SccBase_samples_RigidBodyState *)IN_pose);
   if (-1 == size_IN_buf_pose) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in test_range_RI_updatePose_DM, parameter pose");
      #endif
        /* Crash the application due to message loss */
        abort();
   }


   // Call Middleware interface
   extern void vm_test_range_updatepose_dm
     (void *, size_t);

   vm_test_range_updatepose_dm
     ((void *)&IN_buf_pose, (size_t)size_IN_buf_pose);


}void test_range_RI_updatePose_LS
      (const asn1SccBase_samples_RigidBodyState *IN_pose)

{
   // Check that we are not in the startup transition
   if (2 != test_range_initialized) {
      #ifdef __unix__
         puts("A call to test_range_RI_updatePose_LS was made during system startup.");
         puts("This is not allowed because the system is not yet fully initialized. Please fix your code/models");
      #endif
      // crash the application
      abort();
   }

   #ifdef __unix__
      // Log MSC data on Linux when environment variable is set
      static int innerMsc = -1;
      if (-1 == innerMsc)
         innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
      if (1 == innerMsc) {
         long long msc_time = getTimeInMilliseconds();
         PrintASN1Base_samples_RigidBodyState ("INNERDATA: updatepose_ls::Base_samples_RigidBodyState::pose", IN_pose);
         puts(""); // add newline
         // Log message to vizkit3d_LaserScan (corresponding PI: updatePose)
         printf ("INNER: test_range,vizkit3d_laserscan,updatepose_ls,%lld\n", msc_time);
         fflush(stdout);
      }
   #endif
   // Encode parameter pose
   static asn1SccBase_samples_RigidBodyState IN_buf_pose;
   int size_IN_buf_pose =
      Encode_NATIVE_Base_samples_RigidBodyState
        ((void *)&IN_buf_pose,
          sizeof(asn1SccBase_samples_RigidBodyState),
          (asn1SccBase_samples_RigidBodyState *)IN_pose);
   if (-1 == size_IN_buf_pose) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in test_range_RI_updatePose_LS, parameter pose");
      #endif
        /* Crash the application due to message loss */
        abort();
   }


   // Call Middleware interface
   extern void vm_test_range_updatepose_ls
     (void *, size_t);

   vm_test_range_updatepose_ls
     ((void *)&IN_buf_pose, (size_t)size_IN_buf_pose);


}void test_range_RI_updateSonarBeam
      (const asn1SccBase_samples_SonarBeam *IN_beam)

{
   // Check that we are not in the startup transition
   if (2 != test_range_initialized) {
      #ifdef __unix__
         puts("A call to test_range_RI_updateSonarBeam was made during system startup.");
         puts("This is not allowed because the system is not yet fully initialized. Please fix your code/models");
      #endif
      // crash the application
      abort();
   }

   #ifdef __unix__
      // Log MSC data on Linux when environment variable is set
      static int innerMsc = -1;
      if (-1 == innerMsc)
         innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
      if (1 == innerMsc) {
         long long msc_time = getTimeInMilliseconds();
         PrintASN1Base_samples_SonarBeam ("INNERDATA: updatesonarbeam::Base_samples_SonarBeam::beam", IN_beam);
         puts(""); // add newline
         // Log message to vizkit3d_SonarBeam (corresponding PI: updateSonarBeam)
         printf ("INNER: test_range,vizkit3d_sonarbeam,updatesonarbeam,%lld\n", msc_time);
         fflush(stdout);
      }
   #endif
   // Encode parameter beam
   static asn1SccBase_samples_SonarBeam IN_buf_beam;
   int size_IN_buf_beam =
      Encode_NATIVE_Base_samples_SonarBeam
        ((void *)&IN_buf_beam,
          sizeof(asn1SccBase_samples_SonarBeam),
          (asn1SccBase_samples_SonarBeam *)IN_beam);
   if (-1 == size_IN_buf_beam) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in test_range_RI_updateSonarBeam, parameter beam");
      #endif
        /* Crash the application due to message loss */
        abort();
   }


   // Call Middleware interface
   extern void vm_test_range_updatesonarbeam
     (void *, size_t);

   vm_test_range_updatesonarbeam
     ((void *)&IN_buf_beam, (size_t)size_IN_buf_beam);


}

