/* Body file for function test_Range
 * Generated by TASTE on 2021-06-09 12:03:09
 * Provided interfaces : trigger
 * Required interfaces : updateDepthMap, updateLaserScan, updateOrientation, updatePointCloud, updatePose_DM, updatePose_LS, updateSonarBeam
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 265 199 655 406
 * Timers              : 
 */
#include "test_range_vm_if.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned test_range_initialized = 0;
void init_test_range(void)
{
   if (!test_range_initialized) {
      test_range_initialized = 1;
      // Call user code startup function
      test_range_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function test_Range");
#endif
      test_range_initialized = 2;
   }
}
void test_range_trigger()
{
   //  Directly call user code, no parameters to pass
   extern void test_range_PI_trigger(void);
   test_range_PI_trigger();
   // puts ("test_range_trigger called");
}

