/* Body file for function vizkit3d_RigidBodyState
 * Generated by TASTE on 2021-06-09 11:22:26
 * You can edit this file, it will not be overwritten
 * Provided interfaces : updateRigidBodyState
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 1430 326 1756 486
 * Timers              : 
 */
/* There are no required interfaces for this function... */

