/* Body file for function vizkit3d_RigidBodyState
 * Generated by TASTE on 2021-06-09 11:22:26
 * Provided interfaces : updateRigidBodyState
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 1430 326 1756 486
 * Timers              : 
 */
#include "vizkit3d_rigidbodystate_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned vizkit3d_rigidbodystate_initialized = 0;
void init_vizkit3d_rigidbodystate(void)
{
   if (!vizkit3d_rigidbodystate_initialized) {
      vizkit3d_rigidbodystate_initialized = 1;
      // Call user code startup function
      vizkit3d_rigidbodystate_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function vizkit3d_RigidBodyState");
#endif
      vizkit3d_rigidbodystate_initialized = 2;
   }
}
void vizkit3d_rigidbodystate_updateRigidBodyState
      (const char *IN_rbstate, size_t IN_rbstate_len)

{

   static asn1SccBase_samples_RigidBodyState IN_RBSTATE;
#ifdef __unix__
   asn1SccBase_samples_RigidBodyState_Initialize(&IN_RBSTATE);
#endif
   if (0 != Decode_NATIVE_Base_samples_RigidBodyState (&IN_RBSTATE, (void *)IN_rbstate, IN_rbstate_len)) {
      #ifdef __unix__
         puts("Error decoding Base-samples-RigidBodyState in function vizkit3d_RigidBodyState_updateRigidBodyState");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void vizkit3d_rigidbodystate_PI_updateRigidBodyState
      (const asn1SccBase_samples_RigidBodyState *);




   // Call user code
   vizkit3d_rigidbodystate_PI_updateRigidBodyState (&IN_RBSTATE);

}

