/* Body file for function vizkit3d_SonarBeam
 * Generated by TASTE on 2021-06-09 12:03:09
 * You can edit this file, it will not be overwritten
 * Provided interfaces : updateOrientation, updateSonarBeam
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 1004 757 1394 911
 * Timers              : 
 */
/* There are no required interfaces for this function... */

