/* Body file for function vizkit3d_SonarBeam
 * Generated by TASTE on 2021-06-09 12:03:09
 * Provided interfaces : updateOrientation, updateSonarBeam
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 1004 757 1394 911
 * Timers              : 
 */
#include "vizkit3d_sonarbeam_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned vizkit3d_sonarbeam_initialized = 0;
void init_vizkit3d_sonarbeam(void)
{
   if (!vizkit3d_sonarbeam_initialized) {
      vizkit3d_sonarbeam_initialized = 1;
      // Call user code startup function
      vizkit3d_sonarbeam_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function vizkit3d_SonarBeam");
#endif
      vizkit3d_sonarbeam_initialized = 2;
   }
}
void vizkit3d_sonarbeam_updateOrientation
      (const char *IN_rbs, size_t IN_rbs_len)

{

   static asn1SccBase_samples_RigidBodyState IN_RBS;
#ifdef __unix__
   asn1SccBase_samples_RigidBodyState_Initialize(&IN_RBS);
#endif
   if (0 != Decode_NATIVE_Base_samples_RigidBodyState (&IN_RBS, (void *)IN_rbs, IN_rbs_len)) {
      #ifdef __unix__
         puts("Error decoding Base-samples-RigidBodyState in function vizkit3d_SonarBeam_updateOrientation");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void vizkit3d_sonarbeam_PI_updateOrientation
      (const asn1SccBase_samples_RigidBodyState *);




   // Call user code
   vizkit3d_sonarbeam_PI_updateOrientation (&IN_RBS);

}
void vizkit3d_sonarbeam_updateSonarBeam
      (const char *IN_beam, size_t IN_beam_len)

{

   static asn1SccBase_samples_SonarBeam IN_BEAM;
#ifdef __unix__
   asn1SccBase_samples_SonarBeam_Initialize(&IN_BEAM);
#endif
   if (0 != Decode_NATIVE_Base_samples_SonarBeam (&IN_BEAM, (void *)IN_beam, IN_beam_len)) {
      #ifdef __unix__
         puts("Error decoding Base-samples-SonarBeam in function vizkit3d_SonarBeam_updateSonarBeam");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void vizkit3d_sonarbeam_PI_updateSonarBeam
      (const asn1SccBase_samples_SonarBeam *);




   // Call user code
   vizkit3d_sonarbeam_PI_updateSonarBeam (&IN_BEAM);

}

