/* ASN.1 System configuration file for function vizkit3d_SonarBeam
 * Generated by TASTE on 2021-06-09 12:03:09
 */
#define __NEED_Base_samples_RigidBodyState_NATIVE
#define __NEED_Base_samples_SonarBeam_NATIVE
