
/* Header file for function vizkit3d_DepthMap in CPP language
 * Generated by TASTE on 2021-06-09 12:03:09
 * Context Parameters present : YES
 * Provided interfaces : updateDepthMap, updatePose
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = enabled
  *  |_ Taste::coordinates = 1003 394 1393 553
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void vizkit3d_depthmap_startup(void);

/* Provided interfaces */
void vizkit3d_depthmap_PI_updateDepthMap( const asn1SccBase_samples_DepthMap * );
void vizkit3d_depthmap_PI_updatePose( const asn1SccBase_samples_RigidBodyState * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif

