
/* Header file for function test_Range in CPP language
 * Generated by TASTE on 2021-06-09 12:03:09
 * Context Parameters present : NO
 * Provided interfaces : trigger
 * Required interfaces : updateDepthMap, updateLaserScan, updateOrientation, updatePointCloud, updatePose_DM, updatePose_LS, updateSonarBeam
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = enabled
  *  |_ Taste::coordinates = 265 199 655 406
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void test_range_startup(void);

/* Provided interfaces */
void test_range_PI_trigger( );

/* Required interfaces */
extern void test_range_RI_updateDepthMap( const asn1SccBase_samples_DepthMap * );
extern void test_range_RI_updateLaserScan( const asn1SccBase_samples_LaserScan * );
extern void test_range_RI_updateOrientation( const asn1SccBase_samples_RigidBodyState * );
extern void test_range_RI_updatePointCloud( const asn1SccBase_samples_Pointcloud * );
extern void test_range_RI_updatePose_DM( const asn1SccBase_samples_RigidBodyState * );
extern void test_range_RI_updatePose_LS( const asn1SccBase_samples_RigidBodyState * );
extern void test_range_RI_updateSonarBeam( const asn1SccBase_samples_SonarBeam * );


#ifdef __cplusplus
}
#endif

