/* Body file for function test_BodyState
 * Generated by TASTE on 2021-06-09 11:22:26
 * You can edit this file, it will not be overwritten
 * Provided interfaces : trigger
 * Required interfaces : updateBodyState, updateRigidBodyState
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 524 430 956 650
 * Timers              : 
 */
#include <stdlib.h>
#ifdef __unix__
   #include <stdio.h>
   #include "PrintTypesAsASN1.h"
   #include "timeInMS.h"
#endif
#include "C_ASN1_Types.h"
#include "dataview-uniq.h"

// reference to flag preventing calls to RIs during the startup transition
extern unsigned test_bodystate_initialized;
// in case that happens, use system's abort function to crash the application
extern void abort (void);

void test_bodystate_RI_updateBodyState
      (const asn1SccBase_samples_BodyState *IN_bodystate)

{
   // Check that we are not in the startup transition
   if (2 != test_bodystate_initialized) {
      #ifdef __unix__
         puts("A call to test_bodystate_RI_updateBodyState was made during system startup.");
         puts("This is not allowed because the system is not yet fully initialized. Please fix your code/models");
      #endif
      // crash the application
      abort();
   }

   #ifdef __unix__
      // Log MSC data on Linux when environment variable is set
      static int innerMsc = -1;
      if (-1 == innerMsc)
         innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
      if (1 == innerMsc) {
         long long msc_time = getTimeInMilliseconds();
         PrintASN1Base_samples_BodyState ("INNERDATA: updatebodystate::Base_samples_BodyState::bodystate", IN_bodystate);
         puts(""); // add newline
         // Log message to vizkit3d_BodyState (corresponding PI: updateBodyState)
         printf ("INNER: test_bodystate,vizkit3d_bodystate,updatebodystate,%lld\n", msc_time);
         fflush(stdout);
      }
   #endif
   // Encode parameter bodystate
   static asn1SccBase_samples_BodyState IN_buf_bodystate;
   int size_IN_buf_bodystate =
      Encode_NATIVE_Base_samples_BodyState
        ((void *)&IN_buf_bodystate,
          sizeof(asn1SccBase_samples_BodyState),
          (asn1SccBase_samples_BodyState *)IN_bodystate);
   if (-1 == size_IN_buf_bodystate) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in test_bodystate_RI_updateBodyState, parameter bodystate");
      #endif
        /* Crash the application due to message loss */
        abort();
   }


   // Call Middleware interface
   extern void vm_test_bodystate_updatebodystate
     (void *, size_t);

   vm_test_bodystate_updatebodystate
     ((void *)&IN_buf_bodystate, (size_t)size_IN_buf_bodystate);


}void test_bodystate_RI_updateRigidBodyState
      (const asn1SccBase_samples_RigidBodyState *IN_rbstate)

{
   // Check that we are not in the startup transition
   if (2 != test_bodystate_initialized) {
      #ifdef __unix__
         puts("A call to test_bodystate_RI_updateRigidBodyState was made during system startup.");
         puts("This is not allowed because the system is not yet fully initialized. Please fix your code/models");
      #endif
      // crash the application
      abort();
   }

   #ifdef __unix__
      // Log MSC data on Linux when environment variable is set
      static int innerMsc = -1;
      if (-1 == innerMsc)
         innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
      if (1 == innerMsc) {
         long long msc_time = getTimeInMilliseconds();
         PrintASN1Base_samples_RigidBodyState ("INNERDATA: updaterigidbodystate::Base_samples_RigidBodyState::rbstate", IN_rbstate);
         puts(""); // add newline
         // Log message to vizkit3d_RigidBodyState (corresponding PI: updateRigidBodyState)
         printf ("INNER: test_bodystate,vizkit3d_rigidbodystate,updaterigidbodystate,%lld\n", msc_time);
         fflush(stdout);
      }
   #endif
   // Encode parameter rbstate
   static asn1SccBase_samples_RigidBodyState IN_buf_rbstate;
   int size_IN_buf_rbstate =
      Encode_NATIVE_Base_samples_RigidBodyState
        ((void *)&IN_buf_rbstate,
          sizeof(asn1SccBase_samples_RigidBodyState),
          (asn1SccBase_samples_RigidBodyState *)IN_rbstate);
   if (-1 == size_IN_buf_rbstate) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in test_bodystate_RI_updateRigidBodyState, parameter rbstate");
      #endif
        /* Crash the application due to message loss */
        abort();
   }


   // Call Middleware interface
   extern void vm_test_bodystate_updaterigidbodystate
     (void *, size_t);

   vm_test_bodystate_updaterigidbodystate
     ((void *)&IN_buf_rbstate, (size_t)size_IN_buf_rbstate);


}

