/* Body file for function test_BodyState
 * Generated by TASTE on 2021-06-09 11:22:26
 * Provided interfaces : trigger
 * Required interfaces : updateBodyState, updateRigidBodyState
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 524 430 956 650
 * Timers              : 
 */
#include "test_bodystate_vm_if.h"
#ifdef __unix__
   #include <stdio.h>
#endif




extern void init_vizkit3d_bodystate(void);
extern unsigned vizkit3d_bodystate_initialized;
unsigned test_bodystate_initialized = 0;
void init_test_bodystate(void)
{
   if (!test_bodystate_initialized) {
      test_bodystate_initialized = 1;
      // Call user code startup function
      test_bodystate_startup();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == vizkit3d_bodystate_initialized) {
          init_vizkit3d_bodystate();
      }
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function test_BodyState");
#endif
      test_bodystate_initialized = 2;
   }
}
void test_bodystate_trigger()
{
   //  Directly call user code, no parameters to pass
   extern void test_bodystate_PI_trigger(void);
   test_bodystate_PI_trigger();
   // puts ("test_bodystate_trigger called");
}

