/* Body file for function vizkit3d_BodyState
 * Generated by TASTE on 2021-06-09 11:22:26
 * You can edit this file, it will not be overwritten
 * Provided interfaces : updateBodyState
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 1440 567 1763 724
 * Timers              : 
 */
/* There are no required interfaces for this function... */

