/* Body file for function vizkit3d_BodyState
 * Generated by TASTE on 2021-06-09 11:22:26
 * Provided interfaces : updateBodyState
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = enabled
 *   |_ Taste::coordinates = 1440 567 1763 724
 * Timers              : 
 */
#include "vizkit3d_bodystate_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned vizkit3d_bodystate_initialized = 0;
void init_vizkit3d_bodystate(void)
{
   if (!vizkit3d_bodystate_initialized) {
      vizkit3d_bodystate_initialized = 1;
      // Call user code startup function
      vizkit3d_bodystate_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function vizkit3d_BodyState");
#endif
      vizkit3d_bodystate_initialized = 2;
   }
}
void vizkit3d_bodystate_updateBodyState
      (const char *IN_bodystate, size_t IN_bodystate_len)

{

   asn1SccBase_samples_BodyState IN_BODYSTATE;
#ifdef __unix__
   asn1SccBase_samples_BodyState_Initialize(&IN_BODYSTATE);
#endif
   if (0 != Decode_NATIVE_Base_samples_BodyState (&IN_BODYSTATE, (void *)IN_bodystate, IN_bodystate_len)) {
      #ifdef __unix__
         puts("Error decoding Base-samples-BodyState in function vizkit3d_BodyState_updateBodyState");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void vizkit3d_bodystate_PI_updateBodyState
      (const asn1SccBase_samples_BodyState *);




   // Call user code
   vizkit3d_bodystate_PI_updateBodyState (&IN_BODYSTATE);

}

